Feat/docker file
sedkis/twitter-clone pull request #6
Opened 2022-09-07 15:13 UTC by dle519

created docker file and dockerignore file to containerize the front-end

2022-09-07 15:31 UTC, sedkis requested changes
@dle519  - One thing to add is "Get Started / How to build" instructions that anybody can find in the README

Ie how to build the docker image using the Dockerfile and then how to run the Docker image!

LGTM besides that please!

2022-09-08 01:44 UTC, sedkis commented
@dle519  there's a merge conflict - can you sort please and push?

2022-09-08 14:04 UTC, dle519 commented
@sedkis i think i fixed the merge conflict

2022-09-13 15:13 UTC, sedkis approved these changes

2022-09-13 15:13 UTC, merged